balance/urls.py
from django.urls import path

from .views import (
    IncomeListView,
    IncomeDetailView,
    IncomeCreateView,
    IncomeUpdateView,
    IncomeDeleteView,
    IncomeCategoryListView,
    IncomeCategoryDetailView,
    IncomeCategoryCreateView,
    IncomeCategoryDeleteView,
    IncomeCategoryUpdateView,
    ExpenseListView,
    ExpenseDetailView,
    ExpenseCreateView,
    ExpenseUpdateView,
    ExpenseDeleteView,
    ExpenseCategoryListView,
    ExpenseCategoryDetailView,
    ExpenseCategoryCreateView,
    ExpenseCategoryDeleteView,
    ExpenseCategoryUpdateView,
    DashboardTemplateView,
)

urlpatterns = [
    path("income-list/", IncomeListView.as_view(), name="income_list"),
    path("income-detail/<int:pk>", IncomeDetailView.as_view(), name="income_detail"),
    path("income-create/", IncomeCreateView.as_view(), name="income_create"),
    path("income-update/<int:pk>", IncomeUpdateView.as_view(), name="income_update"),
    path("income-delete/<int:pk>", IncomeDeleteView.as_view(), name="income_delete"),
    path("income-category-list/", IncomeCategoryListView.as_view(), name="income_category_list"),
    path("income-category-detail/<int:pk>", IncomeCategoryDetailView.as_view(), name="income_category_detail"),
    path("income-category-create/", IncomeCategoryCreateView.as_view(), name="income_category_create"),
    path("income-category-update/<int:pk>", IncomeCategoryUpdateView.as_view(), name="income_category_update"),
    path("income-category-delete/<int:pk>", IncomeCategoryDeleteView.as_view(), name="income_category_delete"),

    path("expense-list/", ExpenseListView.as_view(), name="expense_list"),
    path("expense-detail/<int:pk>", ExpenseDetailView.as_view(), name="expense_detail"),
    path("expense-create/", ExpenseCreateView.as_view(), name="expense_create"),
    path("expense-update/<int:pk>", ExpenseUpdateView.as_view(), name="expense_update"),
    path("expense-delete/<int:pk>", ExpenseDeleteView.as_view(), name="expense_delete"),
    path("category-list/", ExpenseCategoryListView.as_view(), name="expense_category_list"),
    path("category-detail/<int:pk>", ExpenseCategoryDetailView.as_view(), name="expense_category_detail"),
    path("category-create/", ExpenseCategoryCreateView.as_view(), name="expense_category_create"),
    path("category-update/<int:pk>", ExpenseCategoryUpdateView.as_view(), name="expense_category_update"),
    path("category-delete/<int:pk>", ExpenseCategoryDeleteView.as_view(), name="expense_category_delete"),
    path("dashboard/", DashboardTemplateView.as_view(), name="dashboard")
]

project_budget/urls.py
from django.contrib import admin
from django.urls import path, include
from user_manager.views import BaseView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", BaseView.as_view(), name='base'),
    path("user/", include("user_manager.urls")),
    path("balance/", include("balance.urls")),
]

balance/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models


class Income(models.Model):
    income_name = models.CharField(max_length=50)
    income_value = models.DecimalField(
        max_digits=10, decimal_places=2, validators=[MinValueValidator(0.01)]
    )
    comment = models.TextField(blank=True)
    recurring_income = models.BooleanField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="incomes")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    income_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    income_category = models.ForeignKey(
        "balance.IncomeCategory", null=True, on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ("-income_date",)

    def __str__(self):
        return self.income_name


class IncomeCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    income_category_name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "Income Categories"

    def __str__(self):
        return self.income_category_name


class Expense(models.Model):
    expense_name = models.CharField(max_length=50)
    expense_value = models.DecimalField(
        max_digits=10, decimal_places=2, validators=[MinValueValidator(0.01)]
    )
    comment = models.TextField(blank=True)
    recurring_expense = models.BooleanField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="expenses")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    expense_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    expense_category = models.ForeignKey(
        "balance.ExpenseCategory", null=True, on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ("-expense_date",)

    def __str__(self):
        return self.expense_name


class ExpenseCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    expense_category_name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ("expense_category_name",)
        verbose_name_plural = "Expense Categories"

    def __str__(self):
        return self.expense_category_name

balance/forms.py
from datetime import date

from django import forms
from django.core.validators import MaxValueValidator

from .models import Income, IncomeCategory, Expense, ExpenseCategory


class ExpenseForm(forms.ModelForm):
    expense_name = forms.CharField(error_messages={"required": "You must name the expense"}, label="Name", widget=forms.TextInput(attrs={'class': 'form-control'}))
    expense_value = forms.DecimalField(error_messages={"required": "You must provide the value of the expense"}, label="Value", widget=forms.NumberInput(attrs={'class': 'form-control'}))
    comment = forms.CharField(label="Comment", widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    expense_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', "placeholder": "YYYY-MM-DD"}), required=False, validators=[MaxValueValidator(date.today())])
    category = forms.ModelChoiceField(queryset=ExpenseCategory.objects.all(), error_messages={"required": "You must choose a category"}, widget=forms.Select(attrs={'class': 'form-control'}))
    recurring_expense = forms.BooleanField(widget=forms.Select(choices=(("YES", "YES"), ('NO', 'NO')), attrs={'class': 'form-control'}))

    class Meta:
        model = Expense
        fields = ["expense_name", "expense_value", "comment", "expense_date", "recurring_expense", "category"]


class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ["income_name", "income_value", "comment"]


class ExpenseCategoryForm(forms.ModelForm):
    expense_category_name = forms.CharField(label="Category name", widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = ExpenseCategory
        fields = ["expense_category_name"]


class IncomeCategoryForm(forms.ModelForm):
    class Meta:
        model = IncomeCategory
        fields = ["income_category_name"]

balance/views.py
from decimal import Decimal

from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)

from .filters import ExpenseFilter, IncomeFilter
from .forms import ExpenseForm, ExpenseCategoryForm
from .mixins import AccessUserMixin
from .models import Expense, ExpenseCategory, Income, IncomeCategory


class IncomeListView(ListView):
    model = Income

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        all_incomes_value = Income.objects.aggregate(sum=Sum("income_value"))
        context["all_incomes_value"] = all_incomes_value["sum"]

        all_incomes_count = Income.objects.count()
        context["all_incomes_count"] = all_incomes_count

        main_filter = IncomeFilter(self.request.GET, queryset=Income.objects.all())
        context['filter'] = main_filter

        results_count = main_filter.qs.count()
        context['results_count'] = results_count

        results_value = main_filter.qs.aggregate(sum=Sum('income_value'))
        context['results_value'] = results_value['sum']

        return context


class ExpenseListView(ListView):
    model = Expense

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        all_expenses_value = Expense.objects.aggregate(sum=Sum("expense_value"))
        context["all_expenses_value"] = all_expenses_value["sum"]

        all_expenses_count = Expense.objects.count()
        context["all_expenses_count"] = all_expenses_count

        main_filter = ExpenseFilter(self.request.GET, queryset=Expense.objects.all())
        context["filter"] = main_filter

        results_count = main_filter.qs.count()
        context["results_count"] = results_count

        results_value = main_filter.qs.aggregate(sum=Sum("expense_value"))
        context["results_value"] = results_value["sum"]

        return context


class IncomeDetailView(AccessUserMixin, DetailView):
    model = Income

    def test_func(self):
        obj = self.get_object()
        return obj.user, self.request.user


class ExpenseDetailView(AccessUserMixin, DetailView):
    model = Expense

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user


class IncomeCreateView(CreateView):
    model = Income
    fields = [
        "income_name",
        "income_value",
        "comment",
        "recurring_income",
        "income_date",
        "income_category",
    ]
    success_url = reverse_lazy("income_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ExpenseCreateView(CreateView):
    model = Expense
    form_class = ExpenseForm

    success_url = reverse_lazy("expense_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ExpenseUpdateView(UpdateView):
    model = Expense
    template_name = "balance/expense_update_form.html"
    form_class = ExpenseForm
    success_url = reverse_lazy("expense_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class IncomeUpdateView(UpdateView):
    model = Income
    template_name = "balance/income_update_form.html"
    fields = [
        "income_name",
        "income_value",
        "comment",
        "recurring_income",
        "income_date",
        "income_category",
    ]
    success_url = reverse_lazy("income_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class IncomeDeleteView(DeleteView):
    model = Income
    success_url = reverse_lazy("income_list")

    def get_queryset(self):
        qs = super(IncomeDeleteView, self).get_queryset()
        return qs.filter(user=self.request.user)


class IncomeCategoryListView(ListView):
    model = IncomeCategory
    template_name = "balance/income_category_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = IncomeCategory.objects.all()
        context['categories'] = categories

        sum_of_incomes_in_category = IncomeCategory.objects.annotate(
            sum=Sum("income__income_value")
        )
        context["sum_of_incomes_in_category"] = sum_of_incomes_in_category
        return context


class IncomeCategoryDetailView(DetailView):
    model = IncomeCategory
    template_name = "balance/income_category_detail.html"


class IncomeCategoryCreateView(CreateView):
    model = IncomeCategory
    fields = ["income_category_name"]
    template_name = "balance/income_category_form.html"
    success_url = reverse_lazy("income_category_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ExpenseDeleteView(DeleteView):
    model = Expense
    success_url = reverse_lazy("expense_list")

    def get_queryset(self):
        qs = super(ExpenseDeleteView, self).get_queryset()
        return qs.filter(user=self.request.user)


class ExpenseCategoryListView(ListView):
    model = ExpenseCategory
    template_name = "balance/expense_category_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = ExpenseCategory.objects.all()
        context['categories'] = categories

        sum_of_expenses_in_category = ExpenseCategory.objects.annotate(
            sum=Sum("expense__expense_value")
        )
        context["sum_of_expenses_in_category"] = sum_of_expenses_in_category
        return context


class ExpenseCategoryDetailView(DetailView):
    model = ExpenseCategory
    template_name = "balance/expense_category_detail.html"


class ExpenseCategoryCreateView(CreateView):
    model = ExpenseCategory
    form_class = ExpenseCategoryForm

    template_name = "balance/expense_category_form.html"
    success_url = reverse_lazy("expense_category_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ExpenseCategoryUpdateView(UpdateView):
    model = ExpenseCategory
    fields = ["expense_category_name"]
    template_name = "balance/expense_category_update_form.html"
    success_url = reverse_lazy("expense_category_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class IncomeCategoryUpdateView(UpdateView):
    model = IncomeCategory
    fields = ["income_category_name"]
    template_name = "balance/income_category_update_form.html"
    success_url = reverse_lazy("income_category_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class IncomeCategoryDeleteView(DeleteView):
    model = IncomeCategory
    template_name = "balance/income_category_confirm_delete.html"
    success_url = reverse_lazy("income_category_list")

    def get_queryset(self):
        qs = super(IncomeCategoryDeleteView, self).get_queryset()
        return qs.filter(user=self.request.user)


class ExpenseCategoryDeleteView(DeleteView):
    model = ExpenseCategory
    template_name = "balance/expense_category_confirm_delete.html"
    success_url = reverse_lazy("expense_category_list")

    def get_queryset(self):
        qs = super(ExpenseCategoryDeleteView, self).get_queryset()
        return qs.filter(user=self.request.user)


class DashboardTemplateView(TemplateView):
    model = Expense, Income
    template_name = 'balance/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        expenses = Expense.objects.all()
        context["expenses"] = expenses

        categories = ExpenseCategory.objects.all()
        context["categories"] = categories

        all_expenses_value = Expense.objects.aggregate(sum=Sum("expense_value"))
        context["all_expenses_value"] = all_expenses_value["sum"].quantize(Decimal('1.00'))

        all_incomes_value = Income.objects.aggregate(sum=Sum("income_value"))
        context["all_incomes_value"] = all_incomes_value["sum"].quantize(Decimal('1.00'))

        sum_of_expenses_in_category = ExpenseCategory.objects.annotate(
            Sum("expense__expense_value"))
        context["sum_of_expenses_in_category"] = sum_of_expenses_in_category

        sum_of_incomes_in_category = IncomeCategory.objects.annotate(Sum("income__income_value"))
        context["sum_of_incomes_in_category"] = sum_of_incomes_in_category

        january_expenses = Expense.objects.filter(expense_date__month=1).aggregate(sum=(Coalesce(Sum("expense_value"), Decimal("0"))))
        context["january_expenses"] = january_expenses["sum"]
        february_expenses = Expense.objects.filter(expense_date__month=2).aggregate(
            sum=(Coalesce(Sum("expense_value"), Decimal("0"))))
        context["february_expenses"] = february_expenses["sum"]
        march_expenses = Expense.objects.filter(expense_date__month=3).aggregate(
            sum=(Coalesce(Sum("expense_value"), Decimal("0"))))
        context["march_expenses"] = march_expenses["sum"]
        april_expenses = Expense.objects.filter(expense_date__month=4).aggregate(
            sum=(Coalesce(Sum("expense_value"), Decimal("0"))))
        context["april_expenses"] = april_expenses["sum"]
        may_expenses = Expense.objects.filter(expense_date__month=5).aggregate(
            sum=(Coalesce(Sum("expense_value"), Decimal("0.0"))))
        context["may_expenses"] = may_expenses["sum"]
        june_expenses = Expense.objects.filter(expense_date__month=6).aggregate(
            sum=(Coalesce(Sum("expense_value"), Decimal("0"))))

balance/templates/balance/expense_category_detail.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Category detail {% endblock %}
{% block page_heading %} Category detail {% endblock page_heading %}

{% block content %}

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Expense</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    {% for expense in expensecategory.expense_set.all %}
    <tr>
        <td>{{ expense }}</td>
        <td>{{ expense.expense_value }}</td>
    </tr>
    </tbody>
    {% empty %}
    No categories yet
    {% endfor %}
</table>
<a href="{% url 'expense_category_delete' expensecategory.id %}" class="btn btn-primary">Delete category</a>
<a href="{% url 'expense_category_update' expensecategory.id %}" class="btn btn-primary">Edit category</a>
<a href="{% url 'expense_category_list' %}" class="btn btn-primary">Back to category list</a>

{% endblock content %}

balance/templates/balance/expense_category_form.html
{% extends 'user_manager/base.html' %}
{% block site_title %} New category {% endblock %}
{% block page_heading %} Add new category {% endblock page_heading %}

{% block content %}

<div class="col-sm-5 mb-4 mb-sm-0">
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'expense_category_list' %}">
        <input type="submit" class="btn btn-primary" value="Save">
        </a>
        <a href="{% url 'expense_category_list' %}" class="btn btn-primary">Cancel</a>
    </form>

{% endblock content %}

balance/templates/balance/expense_category_list.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Categories {% endblock %}
{% block page_heading %} Categories list {% endblock page_heading %}

{% block content %}

<div class="list-group">
    {% for category in sum_of_expenses_in_category %}
    <a href="{% url 'expense_category_detail' category.id %}" class="list-group-item list-group-item-action">{{ category }}{{ category.expense__expense_value__sum }}</a>
            {% empty %}
        No categories yet
        {% endfor %}
</div>

{% endblock content %}

balance/templates/balance/expense_category_update_form.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Category update {% endblock %}
{% block page_heading %} Category update {% endblock page_heading %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Update">
    <a href="{% url 'expense_category_detail' expensecategory.id %}" class="btn btn-primary">Cancel</a>
</form>

{% endblock content %}

balance/templates/balance/expense_confirm_delete.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Confirm {% endblock %}
{% block page_heading %} Confirm deleting {% endblock page_heading %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete expense "{{ object }}"?</p>
    {{ form }}
    <input type="submit" class="btn btn-primary" value="Confirm">
    <a href="{% url 'expense_detail' expense.id %}" class="btn btn-primary">Cancel</a>
</form>

{% endblock content %}

balance/templates/balance/expense_detail.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Expense detail {% endblock %}
{% block page_heading %} Expense detail {% endblock page_heading %}

{% block content %}

<div class="col-sm-4 mb-4 mb-sm-0">
  <div class="card">
    <h5 class="card-header">{{ object.expense_name }}</h5>
      <div class="card-body">
        <h6 class="card-title">Value: {{ object.expense_value }} </h6>
        <h6 class="card-title">Comment: {{ object.comment }} </h6>
        <h6 class="card-title">Date: {{ object.expense_date|date:"Y-m-d" }} </h6>
        <h6 class="card-title">Category: {{ object.expense_category }} </h6>

        <a href="{% url 'expense_delete' expense.id %}" class="btn btn-primary">Delete expense</a>
        <a href="{% url 'expense_update' expense.id %}" class="btn btn-primary">Edit expense</a>
        <a href="{% url 'expense_list' %}" class="btn btn-primary">Back to expense list</a>
     </div>
  </div>
</div>



{% endblock content %}

balance/templates/balance/expense_update_form.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Update expense {% endblock %}
{% block page_heading %} Update expense {% endblock page_heading %}

{% block content %}

<div class="col-sm-5 mb-4 mb-sm-0">
<form method="post" action="" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Update">
    <a href="{% url 'expense_detail' expense.id %}" class="btn btn-primary">Cancel</a>
</form>
</div>

{% endblock content %}

balance/templates/balance/income_category_detail.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Category detail {% endblock %}
{% block page_heading %} Category detail {% endblock page_heading %}

{% block content %}

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Income</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    {% for income in incomecategory.income_set.all %}
    <tr>
        <td>{{ income }}</td>
        <td>{{ income.income_value }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{% url 'income_category_delete' incomecategory.id %}" class="btn btn-primary">Delete category</a>
<a href="{% url 'income_category_update' incomecategory.id %}" class="btn btn-primary">Edit category</a>
<a href="{% url 'income_category_list' %}" class="btn btn-primary">Back to category list</a>

{% endblock content %}

balance/templates/balance/income_category_update_form.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Category update {% endblock %}
{% block page_heading %} Category update {% endblock page_heading %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Update">
    <a href="{% url 'income_category_detail' incomecategory.id %}" class="btn btn-primary">Cancel</a>
</form>

{% endblock content %}

balance/templates/balance/income_confirm_delete.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Confirm {% endblock %}
{% block page_heading %} Confirm deleting {% endblock page_heading %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete income "{{ object }}"?</p>
    {{ form }}
    <input type="submit" class="btn btn-primary" value="Confirm">
    <a href="{% url 'income_detail' income.id %}" class="btn btn-primary">Cancel</a>
</form>

{% endblock content %}

balance/templates/balance/income_detail.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Income detail {% endblock %}
{% block page_heading %} Income detail {% endblock page_heading %}

{% block content %}

Income name: {{ object.income_name }}</br>
Income value: {{ object.income_value }}</br>
Comment: {{ object.comment }}</br>
Income date: {{ object.income.date }}</br>
Category: {{ object.income_category }}</br></p>

<a href="{% url 'income_delete' income.id %}" class="btn btn-primary">Delete income</a>
<a href="{% url 'income_update' income.id %}" class="btn btn-primary">Edit income</a>
<a href="{% url 'income_list' %}" class="btn btn-primary">Back to income list</a>

{% endblock content %}

balance/templates/balance/income_list.html
{% extends 'user_manager/base.html' %}
{% block site_title %} Incomes {% endblock %}
{% block page_heading %} Income list {% endblock page_heading %}


{% block content %}
<div class="row">
<div class="col-sm-12 mb-4 mb-sm-0">
<form method="GET" class="text-align: center">
    {{ filter.form }}
    <p>
    <div class="filter-buttons text-center">
        <button type="submit" class="btn btn-warning">Filter</button>
        <button onclick="location.href='{% url 'income_list' %}'" type="button" class="btn btn-warning">Clear all
            filters </button>

    </div>
    </p>
</form>
</div>
</div>


<div class="container">
    <div class="results text-center">
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Results found</h5>
                        <p class="card-text">{{ results_count }}</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Results value</h5>
                        <p class="card-text">{{ results_value }} PLN</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br>

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th onclick="sortTable(0)">Name</th>
        <th onclick="sortTable(1)">Value</th>
        <th onclick="sortTable(2)">Category</th>
        <th onclick="sortTable(3)">Income date</th>
    </tr>
    </thead>
    <tbody>
    {% for income in filter.qs %}
    <tr>
        <td><a href="{% url 'income_detail' income.id%}">{{ income.income_name }}</a></td>
        <td> {{ income.income_value }}</td>
        <td> {{ income.income_category }}</td>
        <td> {{ income.income_date|date:"Y-m-d H:i" }}</td>
    </tr>
    {% empty %}
    No results found
    {% endfor %}
    </tbody>
</table>
</div>

<p><div class="bottom-buttons text-center col-bg-6">
                <a href="{% url 'income_create' %}" class="btn btn-warning">Add income</a>
                <a href="{% url 'income_category_create' %}" class="btn btn-warning">Add new category</a>
</div></p>

{% endblock content %}

balance/templates/balance/incomecategory_list.html
{% extends 'balance/base_generic.html' %}

{% block content %}
  <h1>Income Category List</h1>
  {% if income_category_list %}
  <ul>
    {% for income_category in income_category_list %}
      <li>
        <a href="{% url 'income_category_detail' income_category.id %}">{{ income_category.title }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no income categories</p>
  {% endif %}
  <a href="{% url 'income_category_add' %}"> Add income category </a>
{% endblock %}